---
title: "Reading Data from the Web"
author: Tanya Butt
output: html_document
  
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## NSDUH 

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)

drug_use_html

drug_use_df = drug_use_html %>%
  html_table() %>% 
  first() %>% 
  slice(-1)  
```

## Star Wars

Get some Star Wars data...

```{r}
sw_url = "https://www.imdb.com/list/ls070150896/"

sw_html = read_html(sw_url)

sw_titles =
  sw_html %>% 
  html_elements(".lister-item-header a") %>%
  html_text()

gross_rev_vec = 
  sw_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

swm_df = 
  tibble(
    title = sw_titles,
    rev = gross_rev_vec)
```

## Napoleon Dynamite 

Dynamite reviews

```{r}
dynamite_url = "https://www.amazon.com/Napoleon-Dynamite-Jon-Heder/dp/B00005JNBQ/ref=cm_cr_arp_d_product_top?ie=UTF8"

dynamite_html = read_html(dynamite_url)

dynamite_review_titles =
  dynamite_html %>% 
  html_elements(".a-text-bold span") %>% 
  html_text()
  
dynamite_stars =
  dynamite_html %>% 
  html_elements(".lister-item-header a") %>%
  html_text()

dynamite_df = 
  tibble(
    title = dynamite_review_titles,
    stars = dynamite_stars
    )
```

## Try some APIs

Get some data from an API about water.
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as_tibble()
```

```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```

```{r}
poke_data = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke_data[["name"]]
poke_data[["height"]]
poke_data[["abilities"]]
```


